[package]
name = "rustasim"
version = "0.1.0"
authors = ["Olivia Brode-Roger <nibr@mit.edu>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/nibrivia/rustasim"

[dependencies]
crossbeam-queue = { git = "https://github.com/nibrivia/crossbeam.git" , branch = "wait" }

[profile.release]
debug = true
