[package]
name = "rustasim"
version = "0.1.0"
authors = ["Olivia Brode-Roger <nibr@mit.edu>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/nibrivia/rustasim"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
radix-heap = "0.3.8"
ringbuf = "0.2.1"
# crossbeam = "0.7.3"
#crossbeam = { git = "https://github.com/stjepang/crossbeam.git", rev = "d1736eff0834302e30bda0d259c920b6d7ed0a58" }
crossbeam = { path = "/home/nibr/crossbeam" }

[profile.release]
debug = true
